### ISSUE TITLE
Location of search bar in mobile view

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#19]
Currently in the mobile view the search bar is placed on top of the app name:
![image](https://user-images.githubusercontent.com/14999738/55163816-dc762d80-5140-11e9-824b-29eefb850371.png)

**Comment by PhilipGriffith** [comment]
One last (super minor!) tweak. In mobile mode (at least as displayed by the browser), the search bar extends beyond the limits of the sidebar:
![image](https://user-images.githubusercontent.com/14999738/58494822-f84b7f00-8143-11e9-9154-83abeb1e9c9a.png)
How to fix? does it have something to do with padding or margins?

**Comment by clintonlunn** [comment]
Is this within the bootstrap-formatting branch? @PhilipGriffith

**Comment by PhilipGriffith** [comment]
I'm about to send you a longer email, but it is now within the master branch, as I merged everything to the master on my machine and then just pushed the changes. I should have done a pull request. Sorry!

**Comment by clintonlunn** [comment]
Thanks I see how you did that now. Yeah I was a little confused because I did not see it as a pull request. Thanks!

**Comment by PhilipGriffith** [comment]
I'm going to consider this done. We need to change the checkboxes to buttons, anyway, which will change things yet again.
