### ISSUE TITLE
Right click on marker

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#20]
Right clicking on a marker triggers the context menu.

**Comment by clintonlunn** [comment]
Not sure if this workaround would apply to us since we are creating so many of markers on map load. 

[contextmenu event on a (circlemarker on a canvas) doesn't prevent browser default menu to appear #5995](https://github.com/Leaflet/Leaflet/issues/5995)

**Comment by PhilipGriffith** [comment]
Yeah, let's go ahead and implement that. Do you even need the console log? Can't it just pass silently?

**Comment by clintonlunn** [comment]
Yeah I will test the implementation of that today. I’m sure the console log is not necessary though.

**Comment by PhilipGriffith** [comment]
I went ahead and implemented this. For future reference, all you need is:
`contextmenu: function(e) {}`
