### ISSUE TITLE
Locate should not track user

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#36]
The locate button should work as a "single-shot" tool: you click it, it finds and zooms to your location, then turns off. Currently, the application requires interaction from the user to turn off the locate feature; this should be automatic.

**Comment by PhilipGriffith** [comment]
Perhaps `lc.stopFollowing()`?
[https://github.com/domoritz/leaflet-locatecontrol#methods](url)

**Comment by clintonlunn** [comment]
Could you clarify this? @PhilipGriffith

**Comment by PhilipGriffith** [comment]
Actually, no, I like your solution better. lol

**Comment by PhilipGriffith** [comment]
Nope, the original issue is the desired result. This is done!
