### ISSUE TITLE
Search Provider text box only spans half the column in mobile mode

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#37]
The Search Provider text box does not take up its complete area when in mobile mode.
This should be fixed with the bootstrap components.

**Comment by clintonlunn** [comment]
This seems to have been fixed.

**Comment by PhilipGriffith** [comment]
The buttons still need some work, but I think you're right about this issue. If anything, it's connected to how the _other_ buttons are also laid out, so it may require a more comprehensive solution.
