### ISSUE TITLE
Search Area Radius text gets cut off in mobile mode

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#38]
Currently, the Searcgh Area Radius dropdown cuts off the text within the box when in mobile mode.
Possible solutions: (1) use less text, (2) remove the 'Search Area Radius' text to the left, (3) change the text to the left into a label (would this change anything?).

**Comment by clintonlunn** [comment]
I removed this text ouside of the dropdown, and inserted it into the value of the dropdown. It fits nicely on both desktop and mobile views

**Comment by PhilipGriffith** [comment]
After looking at this, I went ahead and got rid of the "Search radius" text. The dropdown now has a default value on pageload and after the selection is cleared.
