### ISSUE TITLE
Implement the checkboxes

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#39]
Much like adding a field to the table, these boxes should now run using dummy variables from the address fields, though this will be changed later.
The functionality should cover a case in which the second button selects a subset of the first.

**Comment by PhilipGriffith** [comment]
The checkboxes should also be turned into buttons. Consider implementing the code [here](https://getbootstrap.com/docs/4.3/components/buttons/#checkbox-and-radio-buttons).

**Comment by clintonlunn** [comment]
This has been implemented within the [checkboxes](https://github.com/FREAC/COM/tree/checkboxes) branch. 

Still hammering out the mobile layout of the buttons.

**Comment by clintonlunn** [comment]
This branch was merged into the development branch.

**Comment by PhilipGriffith** [comment]
The button text bleeds over when in mobile landscape mode, but as the functionality has been implemented, I'll put that in another issue entirely.

**Comment by clintonlunn** [comment]
I did not realize we were also configuring for landscape mode in mobile
 I will certainly address that and configuring for landscape mode next.

**Comment by PhilipGriffith** [comment]
No worries! It wasn't made explicit.
