### ISSUE TITLE
Table should be present at page load

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#46]
Given that the table has a fixed height, I see no reason why we shouldn't make it visible at all times. The first time it loads and pushed the 'About' section down the page is a bit jarring, in my opinion.

**Comment by PhilipGriffith** [comment]
In conjunction with this, it would also be good to put the "Results" section stuff in the same div as the table. I we could treat them all as a single unit I think it would make a lot of sense.

**Comment by clintonlunn** [comment]
insertTabulator([]); is executed on page load in order to insert an empty table into the legend panel
