### ISSUE TITLE
Button Layout

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#51]
Could the button layout look like this?

![image](https://user-images.githubusercontent.com/14999738/58827410-f6386300-8610-11e9-98ef-7a5336ae535b.png)

**Comment by shodge17** [comment]
Be sure to look at the two insurance in the "mobile" view.  Currently they run together or overlap so it just looks like one block of code.

**Comment by PhilipGriffith** [comment]
That is the Bootstrap "button group," which is also causing the same issue in the CPEIP layout: it doesn't resize. According to posts online, some think the component is simply broken. Maybe we should try implementing the buttons in a better way?

**Comment by clintonlunn** [comment]
I was able to get these buttons to resize more dynamically. For some reason, the search bar has something funny happening with its autocomplete css which is preventing it from being dynamically resized. After a page refresh, it will occupy the correct space though. 

I found some reading on how to make these buttons turn vertical, but looking at it now, I'm not sure if it would be necessary. See screenshot for more details:

![image](https://user-images.githubusercontent.com/24685932/58922929-38de6600-870b-11e9-89bb-233075acc23b.png)

**Comment by clintonlunn** [comment]
![resize](https://user-images.githubusercontent.com/24685932/58923343-47c61800-870d-11e9-9953-f0d44135ba7d.gif)

**Comment by shodge17** [comment]
Clinton-
take a look at the answer at this link.  it helps quite a bit.
https://stackoverflow.com/questions/19133771/styling-bootstraps-btn-group-justified-adding-margins-and-sizing-vertically/19146734

**Comment by clintonlunn** [comment]
I think I understand what you were getting at before with the buttons running together. Margins can be added to the buttons so that they appear more separated (and still maintain the round corner bootstrap component style), or if the currently block style look is what you like, that's also fine. 

Next, would we want to make it so they stack vertically as a responsive (mobile) behavior?

**Comment by shodge17** [comment]
I dont think so,  the text should be small enough so you can read them both as PDG showed it above.

**Comment by clintonlunn** [comment]
What do you mean with PDG?

**Comment by shodge17** [comment]
that made me laugh... Philip D. Griffith....

**Comment by clintonlunn** [comment]
Haha okay thanks. So the view of how the buttons look now is okay? If so,  would this issue be considered as complete?

**Comment by shodge17** [comment]
If you put some padding around it I think we should be good.

**Comment by clintonlunn** [comment]
Okay. I can do that. And keep them in the square block style?

**Comment by shodge17** [comment]
If you can round them easily, then lets see what that looks like

Stephen W. Hodge
ISPA / FREAC
shodge@fsu.edu
850-597-1139

________________________________

**Comment by shodge17** [comment]
I think I like the rounded buttons better if that is easy to do.

**Comment by clintonlunn** [comment]
It was pretty easy. I don't have access to my computer right now, but you can see the changes in the button-layout branch.

**Comment by clintonlunn** [comment]
Completed within [Locate pull request](https://github.com/FREAC/COM/pull/55).
