### ISSUE TITLE
"locate me" button should also trigger drawing the circle

### ISSUE THREAD

**Issue by shodge17** [FREAC/COM#53]
I thought we had this working at one point.  

Once you are located, the circle at whatever radius is set (or 5 miles if nothing is set) should draw and then do the regular search.

**Comment by clintonlunn** [comment]
I think you are correct that it was implemented previously. I can put this functionality back in.

**Comment by shodge17** [comment]
Clinton - I have a meeting on Monday June 17th that I would like to be able to show this functionality, so lets make sure this is your current priority

**Comment by clintonlunn** [comment]
I have implemented this circle in a separate branch “locate”. It was a simple addition and should be ready to merge in. This issue in combination with #51 should be ready to merge into master if changes are looking good.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shodge17** [comment]
As you know, Philip is going to be out of the country until early August.  I am going to be fine with you pulling / pushing / merging into the master while he is gone.  I am not always going to have time to review everything, so when you are ready to merge things into the master, just do it and let me know.

**Comment by clintonlunn** [comment]
Sounds good. Thanks for giving me the go ahead!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PhilipGriffith** [comment]
Just remember to delete branches after you merge them! ;)

**Comment by clintonlunn** [comment]
Completed within [Locate pull request](https://github.com/FREAC/COM/pull/55)
