### ISSUE TITLE
Geosearch control does not return to original place when address not entered

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/COM#58]
The geosearch control moves to the top if a mobile browser is detected. It returns back to its original place after an address is searched.

BUT, it does not return to its original place if an address is not searched (i.e. the user opens the search bar, but does not enter an address to search. 
![geosearch](https://user-images.githubusercontent.com/24685932/59131604-cfe03380-8940-11e9-9fe6-2b2422f34188.gif)

**Comment by shodge17** [comment]
try putting this code in the $(document).ready section
    if (L.Browser.mobile) {
        $('.geocoder-control').focusout(function () {
            $('.geocoder-control').css({'top': '','left': ''})
        });
    }

**Comment by clintonlunn** [comment]
Nice! That worked great! 👍
