### ISSUE TITLE
put the close button ("x") back on the popup

### ISSUE THREAD

**Issue by shodge17** [FREAC/COM#60]
You will see on my branch when you click on a cluster sometimes the popup covers one of the spiderfied points.  you have to click away from the cluster somewhere to close that popup then reclick the cluster to look at the once covered point.

**Comment by clintonlunn** [comment]
There is a closeButton parameter that was set to false. I reset it to true. 

It also brought to light that we have some repetitive popup declaration code that could be condensed into the createPopup() function. I'll create a to-do item for this.
