### ISSUE TITLE
Results table only shows one result

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#61]
I'm not sure what version of the code is currently running on https://bib.freac.fsu.edu/, but the results table only ever shows _one_ result.

**Comment by shodge17** [comment]
Looks ok now from my phone, did something change?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by PhilipGriffith** [comment]
No, I think it was a caching problem on my machine, as it worked correctly in incognito mode.
My bad!
